### PR TITLE
Set action as failed when Java can't be installed. Fixes #12

### LINKED ISSUE #12: Fail when requested JDK is not found
Hey, I'm not sure if I'm doing something wrong, but the action seems to not fail when I try to request installation of JDK for a platform where it's not available, e.g. installing `ibm@1.8.0` on `macos-latest` in my GH workflow silently passes even though the JDK is not actually installed.

### PR DESCRIPTION
**Pull request by bkabrda**
This marks the action as failed when Java can't be installed. I'm no JS/Github actions expert, but hopefully this would work.

### CODE REVIEW

File: src/install.ts [hunk 1]
```diff
@@ -54,8 +54,16 @@ function installJava(javaVersion: string, jabbaVersion: string) {
     .grep(javaVersion)
     .head({ "-n": 1 })
     .stdout.trim();
+  if (!toInstall) {
+    core.setFailed(`Couldn't find Java ${javaVersion}`);
```
Comment (olafurpg) [inline src/install.ts]:
```suggestion
    core.setFailed(`Couldn't find Java ${javaVersion}. To fix this problem, run 'jabba ls-remote' to see the list of valid Java versions.`);
```

**Comment by bkabrda** [comment]
@olafurpg good comment, I accepted the suggestion. Thanks!

**Comment by bkabrda** [comment]
@olafurpg thanks a lot! Any chance you could do a release soon?
